### ISSUE TITLE
Glitch when used inside asyncio loop

### ISSUE THREAD

**Issue by juli4nb4dillo** [numat/sartorius#9]
We had the following code for reading the scale on a django app:

```python
def read_scale(scale_ip: str) -> float:
    scale = Scale(scale_ip)
    return asyncio.run(scale.get()).get('mass')
```

Using an `asyncio` wrapper to avoid Django's event loop.

However every two or three calls, the scale connection will be rejected or time out.

```bash
Connecting to 192.168.X.X timed out.
```

The obvious solution was to close the `scale` object (since it's an extension of `TCPClient`).

```python
def read_scale(scale_ip: str) -> float:
    with Scale(scale_ip) as scale:
       return asyncio.run(scale.get()).get('mass')
```

However this would produce another failure:

```bash
Event loop is closed
...
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
```

That's because the `with` statement will likely close the `scale` before the call is finished. The simplest solution is to use the `async / await` pattern instead of the `asyncio` wrapping:

```python
async def read_scale(scale_ip: str) -> float:
    with Scale(scale_ip) as scale:
       data = await scale.get()
       return data.get('mass')
```

**Comment by JamesJeffryes** [comment]
FWIW, the old pattern was in use because async Django functions were new in 3.0 I believe

**Comment by juli4nb4dillo** [comment]
Yeah, I figured. Django used to be very weird about async.
